naveteam/react-boilerplate

.eslintrc.json
.rescriptsrc.js
README.md
package.json
yarn.lock

add @babel/plugin-proposal-optional-chaining to the project

feat(optional-chaining): add @babel/plugin-proposal-optional-chaining

---

.rescriptsrc.js
package.json

fix spread operator missing in array breaking build and add a fix on prettier script in package.json

fix(build): fix yarn build script

---

.prettierrc
src/providers/fetchClient.js

chore(prettier): set new configs

---

src/providers/fetchClient.js

- Pode ser adicionado mais rotas ao array quando for fazer o teste e não quiser ser redirecionado para o login;

Routes test on fetchClient

---

.eslintrc.json
.gitignore
.huskyrc.json
.prettierrc.json
.stylelintrc.json
package.json
src/context/auth-context.js
src/context/user-context.js
src/index.js
src/providers/fetchClient.js
src/routes/Login/index.js
src/utils/bootstrap.js

- Fix peer dependencies packages;
- Add lint-staged to project;
- Fix pre-commit and pre-push flow;
- Fix scripts on package.json.
- [Issue 8](https://github.com/naveteam/react-boilerplate/issues/8)

fix(scripts): fix package scripts and add linter on project

---

.rescriptsrc.js
package.json

Change the prettier script path to access all js files on folder hierarchy

style(prettier): prettier script

---

src/App.js
src/helpers/bootstrap.js
src/providers/fetchClient.js

- Fix sentry production config
- Optimize some configs.

Fix sentry production config

---

README.md

- add folder structure on readme

Increment readme

---

package.json
src/components/Button/Button.js
src/components/Column/Column.js
src/components/Input/Input.js
src/components/Input/index.js
src/components/Row/Row.js
src/components/Text/Text.js
src/components/__tests__/__snapshots__/Button.test.js.snap
src/helpers/yup-schemas.js
src/routes/Login/Login.js
src/theme/styles.js

- Remove `formik` and add `react-hook-form`
- Create an input component
- Add some styled-system props to other components

feat(react-hook-form): add react-hook-form and input component

---

.huskyrc.json
package.json

Ajustado problema do prettier passar por todos os arquivos do projeto

fix: use lint staged on pre commit

---

.stylelintrc.json
package.json

Remoção do pacote stylelint por não ser mais usado no projeto

chore(packages): remove stylelint

---

package.json
src/context/auth-context.js
src/helpers/auth.js
src/helpers/constants.js
src/providers/fetchClient.js

Adicionado o módulo de oauth2 do pacote `@naveteam/pandora-frontend` 
Não

feat(oauth2): add oauth2 module from @naveteam/pandora-frontend

---

package.json
src/index.js
src/wdyr.js

Adicionada a lib [why did you render](https://github.com/welldone-software/why-did-you-render) para ter o controle de re-renders desnecessários quando estiver desenvolvendo.

feat(wdyr): add wdyr to prevent unnecessary re-renders

---

src/index.js

Correção de erro na grafia de "production" na inicialização do Sentry.
Não.

fix(index): fix misspelling of production on sentry init

---

.eslintrc.json
src/components/Paginator/Paginator.js
src/routes/UsersList/UsersList.js

- Cria component `Paginator` com estilos e funcionalidades mínimas
https://www.loom.com/share/5d2ed49bdef346cb9cf9ddf02a9642e9

feat(paginator): minimum styles and functionalities

---

src/App.js
src/AuthenticatedApp.js
src/helpers/formatters.js
src/routes/UsersList/UsersList.js
src/routes/UsersList/index.js
src/services/auth.js

- Corrige condição no `App`
- Cria `helper` para formatar `ISO`
- Corrige caminho do arquivo `UsersList`
- Formata data de criação diretamente no `service`

fix: minor adjustments

---

src/components/Modal/Modal.js
src/components/Modal/index.js
src/context/index.js
src/context/modal-context.js
src/routes/Login/Login.js

- Adiciona o hook de useConfirmation modal com o context;
- Adiciona o componente de modal;

feat: add modal context with alert hooks

---

package.json
src/components/Select/Select.js
src/helpers/formatters.js
src/helpers/yup-schemas.js
src/routes/Home/Home.js
src/routes/Login/Login.js
src/routes/UserForm/UserForm.js
src/services/users.js

- Integração com o form de usuários;
- Foi necessário passar a ref do select pois dava erro/warning no console no render do componente;
- Adicionado link na home para ir para a página de criação de usuários;
- Comentado o campo de data de nascimento pois não há esse campo no backend

feat: add integration to users form

---

src/components/Drawer/Drawer.js
src/components/Table/TableRow.js
src/routes/Home/Home.js
src/routes/UserForm/UserForm.js
src/routes/UsersList/UsersList.js
src/services/auth.js
src/services/users.js

- Adiciona integração para o delete de user;
- Adiciona layout para o botão de exclusão de usuário;
- Adiciona integração com o boilerplate de back na listagem de users;

feat(delete): add delete method on users

---

src/components/Paginator/Paginator.js
src/helpers/yup-schemas.js
src/hooks/usePagination.js
src/routes/UserForm/UserForm.js
src/routes/UsersList/UsersList.js
src/services/auth.js

- Descomentado o campo birthdate;
- Ajustes na paginação e nas keys que estavam sendo passadas;
Ps.: Falta um ajuste no back para poder utilizar o birthdate, porém se não passar ele dá erro, por isso já deixei o birthdate ali

chore(adjust-pagination): users list pagination keys and add birthdate

---

src/helpers/yup-schemas.js
src/providers/fetchClient.js
src/routes/UserForm/UserForm.js
src/routes/UsersList/UsersFilters.js
src/services/auth.js

- Adiciona interceptor e remove os params que não tem valor;
- Altera role_id para role

chore: add interceptor on request to filter params
